name: AutoDocs

on:
  push:
    branches:
      - master

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README
        uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          commit_message: Update README.
          output_file_paths: '[./README.md]'
          categories: '[code-block]'
